### ISSUE TITLE
ForgetAllCredentials

### ISSUE THREAD

**Issue by Facundo15** [MizunagiKB/PlayFab_GDScriptSdk#1]
Hello, I have a problem and it is that I cannot find a function like ForgetAllCredentials to close session of the client.
Is there any other function that I missed or something like that? because I can't find anything in the PlayFab API Rest documentation to serve as a reference.

Thanks for the attention

**Comment by MizunagiKB** [comment]
I will answer as far as I can understand.

PlayFab session management is performed using information such as **_EntityToken_** and **_ClientSessionTicket_**.
These are returned by PlayFab Server upon successful login.

So if you want to end the session, just discard these variables so they are no longer accessible.
And if you want to use it again, you can get it by logging in again.

> This is similar to a browser saving the user's login status as a cookie.
> (If you delete cookies or initialize your browser history, you will be logged in again, right?)

This also means that you can act as a different user by using **_EntityToken_** and **_ClientSessionTicket_** properly, so you can log in to multiple users on one terminal.

I hope it will give you a hint to reach the answer.

**Comment by MizunagiKB** [comment]
There is no explicit session closing in my program either.

However, I noticed that it is strange that the session information is not destroyed during the reset process.
So, in my program, I committed something that discards information such as **_EntityToken_** and **_ClientSessionTicket_** during the reset process.

**Comment by Facundo15** [comment]
Ok, I suppose I would have to set entity token and client session token to null, and if that doesn't work, I will know

**Comment by MizunagiKB** [comment]
What is the situation when deleting EntityToken and ClientSessionTicket does not work?

This information is required to be set in the HTTP Header when making a PlayFab request.
If it has been deleted, PlayFab will return the following error and all APIs that require authentication will fail.


_ex1) If you did not send X-Authorization._
```
{
  "code": 401,
  "error: "NotAuthenticated",
  "errorCode": 1074,
  "errorMessage": "Not Authenticated",
  "status": "Unauthorized"
}
```

_ex2) If you send an invalid ClientSessionTicket to X-Authorization._ 
```
{
  "code": 401,
  "error": "NotAuthenticated",
  "errorCode": 1074,
  "errorMessage": "X-Authentication HTTP header contains invalid ticket",
  "status": "Unauthorized"
}
```

Does it mean that it may work even if you do not specify the HTTP Header or enter an invalid value?
