### ISSUE TITLE
PlayFab Multiplayer SDK and PlayFab Party SDK are integrated into the SDK for godot?

### ISSUE THREAD

**Issue by Facundo15** [MizunagiKB/PlayFab_GDScriptSdk#2]
Hi I would like to try to make a very simple multiplayer game just to test how multiplayer works with PlayFab and I would like to know if the PlayFab Party SDK and PlayFab multiplayer are already built into the godot SDK or do I have to create a separate module.

**Comment by MizunagiKB** [comment]
The program I created does not include features related to **PlayFab Party**.
It's not as easy as **PlayFab Party**, but if you use _Dedicated Server,_ you can use **Multiplayer API**.

https://docs.microsoft.com/en-us/rest/api/playfab/multiplayer/

It is defined in the following script.
* PlayFabAPI_Matchmaker.gd
* PlayFabAPI_Multiplayer.gd

The Multiplayer API is long to explain, but you can do the following:

1. Register players in the matching list.
1. When matching is established, start the pre-registered _Dedicated Server_ (PlayFab does this).
1. Each player receives a destination address to the _Dedicated Server_.
1. Connect to the _Dedicated Server_ and start the game.

However, the Multiplayer API is a paid service and I have never used it.
